package com.casecollaborative.engine.service.generator;

import com.casecollaborative.engine.model.entity.*;
import com.casecollaborative.engine.repository.AtributoRepository;
import com.casecollaborative.engine.repository.ClaseRepository;
import com.casecollaborative.engine.repository.RelacionClaseRepository;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class SpringBootPostgresGeneratorService implements BackendGeneratorStrategy {

    private final ClaseRepository claseRepository;
    private final AtributoRepository atributoRepository;
    private final RelacionClaseRepository relacionRepository;

    public SpringBootPostgresGeneratorService(ClaseRepository claseRepository,
                                              AtributoRepository atributoRepository,
                                              RelacionClaseRepository relacionRepository) {
        this.claseRepository = claseRepository;
        this.atributoRepository = atributoRepository;
        this.relacionRepository = relacionRepository;
    }

    @Override
    public String getTargetIdentifier() {
        return "SPRING_BOOT_POSTGRES";
    }

    @Override
    public String generarScriptDdl(DiagramaUml diagrama) {
        StringBuilder ddl = new StringBuilder("-- =============================================================\n");
        ddl.append("-- DDL Generado Automáticamente por CASE Collaborative Engine (OMT Standard)\n");
        ddl.append("-- Dialecto: PostgreSQL / Java 21 / Spring Boot 3\n");
        ddl.append("-- =============================================================\n\n");

        List<Clase> clases = claseRepository.findByDiagramaId(diagrama.getId());
        List<RelacionClase> relaciones = relacionRepository.findByDiagramaId(diagrama.getId());

        for (Clase clase : clases) {
            String tableName = sanitizeIdentifier(clase.getNombre());
            ddl.append("CREATE TABLE IF NOT EXISTS ").append(tableName).append(" (\n");

            List<Atributo> atributos = atributoRepository.findByClaseId(clase.getId());
            boolean hasPk = atributos.stream().anyMatch(a -> Boolean.TRUE.equals(a.getEsPk()));

            if (!hasPk) {
                ddl.append("    id BIGSERIAL PRIMARY KEY");
                if (!atributos.isEmpty() || hasForeignKeys(clase, relaciones)) {
                    ddl.append(",\n");
                } else {
                    ddl.append("\n");
                }
            }

            for (int i = 0; i < atributos.size(); i++) {
                Atributo attr = atributos.get(i);
                String colName = sanitizeIdentifier(attr.getNombre());
                String sqlType = mapJavaTypeToSql(normalizeJavaType(attr.getTipoDato()));

                ddl.append("    ").append(colName).append(" ").append(sqlType);

                if (Boolean.TRUE.equals(attr.getEsPk())) {
                    if ("BIGINT".equalsIgnoreCase(sqlType)) {
                        ddl.append(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
                    } else if ("INT".equalsIgnoreCase(sqlType) || "INTEGER".equalsIgnoreCase(sqlType)) {
                        ddl.append(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
                    } else {
                        ddl.append(" PRIMARY KEY");
                    }
                }

                if (i < atributos.size() - 1 || hasForeignKeys(clase, relaciones)) {
                    ddl.append(",\n");
                } else {
                    ddl.append("\n");
                }
            }

            appendForeignKeys(ddl, clase, relaciones);
            ddl.append(");\n\n");
        }

        // Many-to-Many Join Tables
        for (RelacionClase rel : relaciones) {
            if ("HERENCIA".equalsIgnoreCase(rel.getTipoRelacion()) || "CLASE_ASOCIACION".equalsIgnoreCase(rel.getTipoRelacion())) {
                continue;
            }
            // Si existe una clase de asociación vinculada a esta relación, NO generar tabla intermedia genérica
            boolean hasAssocClass = relaciones.stream().anyMatch(ar -> 
                "CLASE_ASOCIACION".equalsIgnoreCase(ar.getTipoRelacion()) &&
                (ar.getClaseDestino().getId().equals(rel.getClaseOrigen().getId()) || ar.getClaseDestino().getId().equals(rel.getClaseDestino().getId()))
            );
            if (hasAssocClass) {
                continue;
            }

            if (isMany(rel.getCardinalidadOrigen()) && isMany(rel.getCardinalidadDestino())) {
                String tableA = sanitizeIdentifier(rel.getClaseOrigen().getNombre());
                String tableB = sanitizeIdentifier(rel.getClaseDestino().getNombre());
                String joinTableName = tableA + "_" + tableB;

                ddl.append("CREATE TABLE IF NOT EXISTS ").append(joinTableName).append(" (\n");
                ddl.append("    ").append(tableA).append("_id BIGINT NOT NULL,\n");
                ddl.append("    ").append(tableB).append("_id BIGINT NOT NULL,\n");
                ddl.append("    PRIMARY KEY (").append(tableA).append("_id, ").append(tableB).append("_id),\n");
                ddl.append("    CONSTRAINT fk_").append(joinTableName).append("_").append(tableA)
                   .append(" FOREIGN KEY (").append(tableA).append("_id) REFERENCES ").append(tableA).append("(id) ON DELETE CASCADE,\n");
                ddl.append("    CONSTRAINT fk_").append(joinTableName).append("_").append(tableB)
                   .append(" FOREIGN KEY (").append(tableB).append("_id) REFERENCES ").append(tableB).append("(id) ON DELETE CASCADE\n");
                ddl.append(");\n\n");
            }
        }

        return ddl.toString();
    }

    private List<Clase> getAssociationPeers(Clase assocClass, List<RelacionClase> relaciones) {
        List<Clase> peers = new ArrayList<>();
        for (RelacionClase r : relaciones) {
            if ("CLASE_ASOCIACION".equalsIgnoreCase(r.getTipoRelacion())) {
                Clase dest = null;
                if (r.getClaseOrigen().getId().equals(assocClass.getId())) {
                    dest = r.getClaseDestino();
                } else if (r.getClaseDestino().getId().equals(assocClass.getId())) {
                    dest = r.getClaseOrigen();
                }
                if (dest != null) {
                    if (!peers.contains(dest)) peers.add(dest);
                    for (RelacionClase rb : relaciones) {
                        if (!"CLASE_ASOCIACION".equalsIgnoreCase(rb.getTipoRelacion()) && !"HERENCIA".equalsIgnoreCase(rb.getTipoRelacion())) {
                            if (rb.getClaseOrigen().getId().equals(dest.getId())) {
                                if (!peers.contains(rb.getClaseDestino()) && !rb.getClaseDestino().getId().equals(assocClass.getId())) {
                                    peers.add(rb.getClaseDestino());
                                }
                            } else if (rb.getClaseDestino().getId().equals(dest.getId())) {
                                if (!peers.contains(rb.getClaseOrigen()) && !rb.getClaseOrigen().getId().equals(assocClass.getId())) {
                                    peers.add(rb.getClaseOrigen());
                                }
                            }
                        }
                    }
                }
            }
        }
        return peers;
    }

    private boolean isMany(String cardinality) {
        if (cardinality == null) return false;
        String c = cardinality.trim().toLowerCase();
        return c.equals("*") || c.equals("n") || c.equals("m") || c.contains("*") || c.contains("n") || c.contains("m") || c.endsWith("..*");
    }

    private boolean isOne(String cardinality) {
        if (cardinality == null) return true;
        String c = cardinality.trim().toLowerCase();
        return c.equals("1") || c.equals("0..1") || c.equals("1..1") || (!isMany(c));
    }

    private boolean hasForeignKeys(Clase clase, List<RelacionClase> relaciones) {
        if (!getAssociationPeers(clase, relaciones).isEmpty()) {
            return true;
        }
        return relaciones.stream().anyMatch(r ->
            (r.getClaseOrigen().getId().equals(clase.getId()) && "HERENCIA".equalsIgnoreCase(r.getTipoRelacion())) ||
            (r.getClaseOrigen().getId().equals(clase.getId()) && isOne(r.getCardinalidadDestino()) && isMany(r.getCardinalidadOrigen())) ||
            (r.getClaseDestino().getId().equals(clase.getId()) && isOne(r.getCardinalidadOrigen()) && isMany(r.getCardinalidadDestino()))
        );
    }

    private void appendForeignKeys(StringBuilder ddl, Clase clase, List<RelacionClase> relaciones) {
        List<Clase> assocPeers = getAssociationPeers(clase, relaciones);
        if (!assocPeers.isEmpty()) {
            for (int i = 0; i < assocPeers.size(); i++) {
                Clase peer = assocPeers.get(i);
                String otherTable = sanitizeIdentifier(peer.getNombre());
                ddl.append("    ").append(otherTable).append("_id BIGINT,\n");
                ddl.append("    CONSTRAINT fk_").append(sanitizeIdentifier(clase.getNombre())).append("_").append(otherTable)
                   .append(" FOREIGN KEY (").append(otherTable).append("_id) REFERENCES ").append(otherTable).append("(id) ON DELETE CASCADE");
                if (i < assocPeers.size() - 1) {
                    ddl.append(",\n");
                } else {
                    ddl.append("\n");
                }
            }
            return;
        }

        List<RelacionClase> fks = relaciones.stream()
            .filter(r -> (r.getClaseOrigen().getId().equals(clase.getId()) && "HERENCIA".equalsIgnoreCase(r.getTipoRelacion())) ||
                         (r.getClaseOrigen().getId().equals(clase.getId()) && isOne(r.getCardinalidadDestino()) && isMany(r.getCardinalidadOrigen())) ||
                         (r.getClaseDestino().getId().equals(clase.getId()) && isOne(r.getCardinalidadOrigen()) && isMany(r.getCardinalidadDestino())))
            .collect(Collectors.toList());

        for (int i = 0; i < fks.size(); i++) {
            RelacionClase fk = fks.get(i);
            if ("HERENCIA".equalsIgnoreCase(fk.getTipoRelacion()) && fk.getClaseOrigen().getId().equals(clase.getId())) {
                String parentTable = sanitizeIdentifier(fk.getClaseDestino().getNombre());
                ddl.append("    CONSTRAINT fk_inherits_").append(parentTable)
                   .append(" FOREIGN KEY (id) REFERENCES ").append(parentTable).append("(id) ON DELETE CASCADE");
            } else {
                String otherTable = fk.getClaseOrigen().getId().equals(clase.getId()) ?
                        sanitizeIdentifier(fk.getClaseDestino().getNombre()) :
                        sanitizeIdentifier(fk.getClaseOrigen().getNombre());
                ddl.append("    ").append(otherTable).append("_id BIGINT,\n");
                ddl.append("    CONSTRAINT fk_").append(sanitizeIdentifier(clase.getNombre())).append("_").append(otherTable)
                   .append(" FOREIGN KEY (").append(otherTable).append("_id) REFERENCES ").append(otherTable).append("(id) ON DELETE SET NULL");
            }

            if (i < fks.size() - 1) {
                ddl.append(",\n");
            } else {
                ddl.append("\n");
            }
        }
    }

    @Override
    public byte[] generarProyecto(DiagramaUml diagrama) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             ZipOutputStream zos = new ZipOutputStream(baos)) {

            String basePackage = "com.generated.app";
            String basePath = basePackage.replace(".", "/") + "/";

            // 1. Build and Maven Configuration
            addZipEntry(zos, "pom.xml", generarPomXml());
            addZipEntry(zos, ".gitignore", generarGitIgnore());
            addZipEntry(zos, "README.md", generarReadme(diagrama));

            // 2. Application Configuration & DDL
            addZipEntry(zos, "src/main/resources/application.yml", generarApplicationYml(diagrama));
            addZipEntry(zos, "src/main/resources/schema.sql", generarScriptDdl(diagrama));

            // 3. Application Main & Configurations
            addZipEntry(zos, "src/main/java/" + basePath + "Application.java", generarApplicationJava(basePackage));
            addZipEntry(zos, "src/main/java/" + basePath + "config/CorsConfig.java", generarCorsConfig(basePackage));

            List<Clase> clases = claseRepository.findByDiagramaId(diagrama.getId());
            List<RelacionClase> relaciones = relacionRepository.findByDiagramaId(diagrama.getId());

            for (Clase clase : clases) {
                List<Atributo> atributos = atributoRepository.findByClaseId(clase.getId());

                // Entity
                addZipEntry(zos, "src/main/java/" + basePath + "entity/" + clase.getNombre() + ".java",
                    generarEntity(basePackage, clase, atributos, relaciones));

                // DTOs
                addZipEntry(zos, "src/main/java/" + basePath + "dto/" + clase.getNombre() + "RequestDTO.java",
                    generarRequestDto(basePackage, clase, atributos));
                addZipEntry(zos, "src/main/java/" + basePath + "dto/" + clase.getNombre() + "ResponseDTO.java",
                    generarResponseDto(basePackage, clase, atributos));

                // Repository
                addZipEntry(zos, "src/main/java/" + basePath + "repository/" + clase.getNombre() + "Repository.java",
                    generarRepository(basePackage, clase, atributos));

                // Service (Full CRUD)
                addZipEntry(zos, "src/main/java/" + basePath + "service/" + clase.getNombre() + "Service.java",
                    generarService(basePackage, clase, atributos));

                // Controller (Full CRUD)
                addZipEntry(zos, "src/main/java/" + basePath + "controller/" + clase.getNombre() + "Controller.java",
                    generarController(basePackage, clase, atributos));
            }

            zos.finish();
            return baos.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Error al generar el proyecto ZIP procedural", e);
        }
    }

    private void addZipEntry(ZipOutputStream zos, String path, String content) throws Exception {
        ZipEntry entry = new ZipEntry(path);
        zos.putNextEntry(entry);
        zos.write(content.getBytes(StandardCharsets.UTF_8));
        zos.closeEntry();
    }

    // =========================================================================
    // TEMPLATES & CODE SYNTHESIS
    // =========================================================================

    private String generarPomXml() {
        return """
            <?xml version="1.0" encoding="UTF-8"?>
            <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                <modelVersion>4.0.0</modelVersion>
                <parent>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-parent</artifactId>
                    <version>3.2.4</version>
                    <relativePath/>
                </parent>
                <groupId>com.generated</groupId>
                <artifactId>app</artifactId>
                <version>0.0.1-SNAPSHOT</version>
                <name>Generated Backend Application</name>
                <description>Backend REST API sintetizado proceduralmente por CASE Collaborative Engine</description>

                <properties>
                    <java.version>21</java.version>
                </properties>

                <dependencies>
                    <!-- Spring Boot Starters -->
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-web</artifactId>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-data-jpa</artifactId>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-validation</artifactId>
                    </dependency>

                    <!-- PostgreSQL Database Driver -->
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <scope>runtime</scope>
                    </dependency>

                    <!-- Lombok -->
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <optional>true</optional>
                    </dependency>

                    <!-- Spring Boot Starter Test -->
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-test</artifactId>
                        <scope>test</scope>
                    </dependency>
                </dependencies>

                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>3.11.0</version>
                            <configuration>
                                <source>21</source>
                                <target>21</target>
                                <annotationProcessorPaths>
                                    <path>
                                        <groupId>org.projectlombok</groupId>
                                        <artifactId>lombok</artifactId>
                                        <version>${lombok.version}</version>
                                    </path>
                                </annotationProcessorPaths>
                            </configuration>
                        </plugin>
                        <plugin>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-maven-plugin</artifactId>
                            <configuration>
                                <excludes>
                                    <exclude>
                                        <groupId>org.projectlombok</groupId>
                                        <artifactId>lombok</artifactId>
                                    </exclude>
                                </excludes>
                            </configuration>
                        </plugin>
                    </plugins>
                </build>
            </project>
            """;
    }

    private String generarApplicationYml(DiagramaUml diagrama) {
        String dbName = "case_" + (diagrama.getProyecto() != null ? sanitizeIdentifier(diagrama.getProyecto().getNombre()) : "app_db");
        return """
            spring:
              application:
                name: generated-backend-app
              datasource:
                url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/%s}
                username: ${SPRING_DATASOURCE_USERNAME:postgres}
                password: ${SPRING_DATASOURCE_PASSWORD:postgres}
                driver-class-name: org.postgresql.Driver
              jpa:
                hibernate:
                  ddl-auto: update
                show-sql: true
                properties:
                  hibernate:
                    format_sql: true
            server:
              port: ${PORT:8081}
            """.formatted(dbName);
    }

    private String generarGitIgnore() {
        return """
            target/
            !.mvn/wrapper/maven-wrapper.jar
            !**/src/main/**/target/
            !**/src/test/**/target/
            .idea/
            *.iml
            .vscode/
            .settings/
            .project
            .classpath
            *.log
            """;
    }

    private String generarReadme(DiagramaUml diagrama) {
        return """
            # Proyecto Backend Generado (Spring Boot 3 / Java 21)

            Este proyecto fue sintetizado proceduralmente por **CASE Collaborative Engine**.
            Es una API REST completa y autónoma lista para ejecución local y despliegue en producción.

            ---

            ## Requisitos Previos
            - **Java 21 JDK** o superior.
            - **Apache Maven 3.8+**.
            - **PostgreSQL 14+** (o contenedor Docker).

            ---

            ## Configuración y Variables de Entorno

            El proyecto soporta configuración dinámica mediante variables de entorno con valores por defecto locales:

            | Variable | Descripción | Valor por Defecto |
            |---|---|---|
            | `SPRING_DATASOURCE_URL` | URL JDBC de conexión | `jdbc:postgresql://localhost:5432/case_db` |
            | `SPRING_DATASOURCE_USERNAME` | Usuario de PostgreSQL | `postgres` |
            | `SPRING_DATASOURCE_PASSWORD` | Contraseña de PostgreSQL | `postgres` |
            | `PORT` | Puerto de escucha del servidor | `8081` |

            ---

            ## Instrucciones de Compilación y Ejecución

            1. **Compilar el proyecto:**
               ```bash
               mvn clean compile
               ```

            2. **Iniciar la aplicación:**
               ```bash
               mvn spring-boot:run
               ```

            3. **Empaquetar archivo JAR ejecutable:**
               ```bash
               mvn clean package -DskipTests
               java -jar target/app-0.0.1-SNAPSHOT.jar
               ```

            ---

            ## Endpoints CRUD Disponibles

            Todos los controladores implementan el ciclo de vida RESTful canónico:
            - `GET /api/{entidad}` : Listar todos (200 OK)
            - `GET /api/{entidad}/{id}` : Obtener por ID (200 OK / 404 Not Found)
            - `POST /api/{entidad}` : Crear nuevo registro (201 Created)
            - `PUT /api/{entidad}/{id}` : Actualizar registro (200 OK / 404 Not Found)
            - `DELETE /api/{entidad}/{id}` : Eliminar registro (204 No Content / 404 Not Found)
            """;
    }

    private String generarApplicationJava(String basePackage) {
        return """
            package %s;

            import org.springframework.boot.SpringApplication;
            import org.springframework.boot.autoconfigure.SpringBootApplication;

            @SpringBootApplication
            public class Application {
                public static void main(String[] args) {
                    SpringApplication.run(Application.class, args);
                }
            }
            """.formatted(basePackage);
    }

    private String generarCorsConfig(String basePackage) {
        return """
            package %s.config;

            import org.springframework.context.annotation.Bean;
            import org.springframework.context.annotation.Configuration;
            import org.springframework.web.servlet.config.annotation.CorsRegistry;
            import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

            @Configuration
            public class CorsConfig {

                @Bean
                public WebMvcConfigurer corsConfigurer() {
                    return new WebMvcConfigurer() {
                        @Override
                        public void addCorsMappings(CorsRegistry registry) {
                            registry.addMapping("/**")
                                    .allowedOriginPatterns("*")
                                    .allowedMethods("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS")
                                    .allowedHeaders("*")
                                    .allowCredentials(true);
                        }
                    };
                }
            }
            """.formatted(basePackage);
    }

    private String generarEntity(String basePackage, Clase clase, List<Atributo> atributos, List<RelacionClase> relaciones) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".entity;\n\n");
        sb.append("import jakarta.persistence.*;\n");
        sb.append("import lombok.*;\n");

        Set<String> typeImports = collectTypeImports(atributos);
        for (String imp : typeImports) {
            sb.append(imp).append("\n");
        }

        boolean hasManyToMany = relaciones.stream().anyMatch(r -> !"HERENCIA".equalsIgnoreCase(r.getTipoRelacion()) && !"CLASE_ASOCIACION".equalsIgnoreCase(r.getTipoRelacion()) && isMany(r.getCardinalidadOrigen()) && isMany(r.getCardinalidadDestino()));
        if (hasManyToMany) {
            sb.append("import java.util.List;\n");
            sb.append("import java.util.ArrayList;\n");
        }
        sb.append("\n");

        sb.append("@Entity\n");
        sb.append("@Table(name = \"").append(sanitizeIdentifier(clase.getNombre())).append("\")\n");
        sb.append("@Getter\n@Setter\n@NoArgsConstructor\n@AllArgsConstructor\n@Builder\n");

        boolean isSuperClass = relaciones.stream().anyMatch(r -> "HERENCIA".equalsIgnoreCase(r.getTipoRelacion()) && r.getClaseDestino().getId().equals(clase.getId()));
        if (isSuperClass) {
            sb.append("@Inheritance(strategy = InheritanceType.JOINED)\n");
        }

        sb.append("public class ").append(clase.getNombre());

        boolean isSubClass = relaciones.stream().anyMatch(r -> "HERENCIA".equalsIgnoreCase(r.getTipoRelacion()) && r.getClaseOrigen().getId().equals(clase.getId()));
        if (isSubClass) {
            RelacionClase parentRel = relaciones.stream().filter(r -> "HERENCIA".equalsIgnoreCase(r.getTipoRelacion()) && r.getClaseOrigen().getId().equals(clase.getId())).findFirst().get();
            sb.append(" extends ").append(parentRel.getClaseDestino().getNombre());
        }
        sb.append(" {\n\n");

        boolean hasExplicitPk = atributos.stream().anyMatch(a -> Boolean.TRUE.equals(a.getEsPk()));
        if (!hasExplicitPk && !isSubClass) {
            sb.append("    @Id\n");
            sb.append("    @GeneratedValue(strategy = GenerationType.IDENTITY)\n");
            sb.append("    private Long id;\n\n");
        }

        for (Atributo a : atributos) {
            String fieldName = sanitizeCamelCase(a.getNombre());
            String javaType = normalizeJavaType(a.getTipoDato());

            if (Boolean.TRUE.equals(a.getEsPk())) {
                sb.append("    @Id\n");
                if ("Long".equals(javaType) || "Integer".equals(javaType)) {
                    sb.append("    @GeneratedValue(strategy = GenerationType.IDENTITY)\n");
                }
            }
            sb.append("    @Column(name = \"").append(sanitizeIdentifier(a.getNombre())).append("\")\n");
            sb.append("    private ").append(javaType).append(" ").append(fieldName).append(";\n\n");
        }

        List<Clase> assocPeers = getAssociationPeers(clase, relaciones);
        if (!assocPeers.isEmpty()) {
            for (Clase peer : assocPeers) {
                String targetClass = peer.getNombre();
                String targetField = sanitizeCamelCase(targetClass);
                sb.append("    @ManyToOne(fetch = FetchType.LAZY)\n");
                sb.append("    @JoinColumn(name = \"").append(sanitizeIdentifier(targetClass)).append("_id\")\n");
                sb.append("    private ").append(targetClass).append(" ").append(targetField).append(";\n\n");
            }
        }

        for (RelacionClase rel : relaciones) {
            if ("HERENCIA".equalsIgnoreCase(rel.getTipoRelacion()) || "CLASE_ASOCIACION".equalsIgnoreCase(rel.getTipoRelacion())) continue;

            if (isMany(rel.getCardinalidadOrigen()) && isMany(rel.getCardinalidadDestino())) {
                boolean hasAssocClass = relaciones.stream().anyMatch(r ->
                    "CLASE_ASOCIACION".equalsIgnoreCase(r.getTipoRelacion()) &&
                    (r.getClaseOrigen().getId().equals(rel.getClaseOrigen().getId()) || r.getClaseOrigen().getId().equals(rel.getClaseDestino().getId()) ||
                     r.getClaseDestino().getId().equals(rel.getClaseOrigen().getId()) || r.getClaseDestino().getId().equals(rel.getClaseDestino().getId()))
                );

                if (!hasAssocClass && rel.getClaseOrigen().getId().equals(clase.getId())) {
                    String targetClass = rel.getClaseDestino().getNombre();
                    String targetField = sanitizeCamelCase(targetClass) + "List";
                    String joinTable = sanitizeIdentifier(clase.getNombre()) + "_" + sanitizeIdentifier(targetClass);

                    sb.append("    @ManyToMany\n");
                    sb.append("    @JoinTable(\n");
                    sb.append("        name = \"").append(joinTable).append("\",\n");
                    sb.append("        joinColumns = @JoinColumn(name = \"").append(sanitizeIdentifier(clase.getNombre())).append("_id\"),\n");
                    sb.append("        inverseJoinColumns = @JoinColumn(name = \"").append(sanitizeIdentifier(targetClass)).append("_id\")\n");
                    sb.append("    )\n");
                    sb.append("    @Builder.Default\n");
                    sb.append("    private List<").append(targetClass).append("> ").append(targetField).append(" = new ArrayList<>();\n\n");
                }
            } else if (isOne(rel.getCardinalidadDestino()) && isMany(rel.getCardinalidadOrigen())) {
                if (rel.getClaseOrigen().getId().equals(clase.getId())) {
                    String targetClass = rel.getClaseDestino().getNombre();
                    String targetField = sanitizeCamelCase(targetClass);
                    sb.append("    @ManyToOne(fetch = FetchType.LAZY)\n");
                    sb.append("    @JoinColumn(name = \"").append(sanitizeIdentifier(targetClass)).append("_id\")\n");
                    sb.append("    private ").append(targetClass).append(" ").append(targetField).append(";\n\n");
                }
            } else if (isOne(rel.getCardinalidadOrigen()) && isMany(rel.getCardinalidadDestino())) {
                if (rel.getClaseDestino().getId().equals(clase.getId())) {
                    String targetClass = rel.getClaseOrigen().getNombre();
                    String targetField = sanitizeCamelCase(targetClass);
                    sb.append("    @ManyToOne(fetch = FetchType.LAZY)\n");
                    sb.append("    @JoinColumn(name = \"").append(sanitizeIdentifier(targetClass)).append("_id\")\n");
                    sb.append("    private ").append(targetClass).append(" ").append(targetField).append(";\n\n");
                }
            }
        }

        sb.append("}\n");
        return sb.toString();
    }

    private String generarRequestDto(String basePackage, Clase clase, List<Atributo> atributos) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".dto;\n\n");

        Set<String> typeImports = collectTypeImports(atributos);
        for (String imp : typeImports) {
            sb.append(imp).append("\n");
        }
        sb.append("\n");

        sb.append("public record ").append(clase.getNombre()).append("RequestDTO(\n");

        List<Atributo> nonPkAttributes = atributos.stream()
                .filter(a -> !Boolean.TRUE.equals(a.getEsPk()) && !a.getNombre().equalsIgnoreCase("id"))
                .collect(Collectors.toList());

        List<Atributo> targetList = nonPkAttributes.isEmpty() ? atributos : nonPkAttributes;

        for (int i = 0; i < targetList.size(); i++) {
            Atributo a = targetList.get(i);
            String javaType = normalizeJavaType(a.getTipoDato());
            String fieldName = sanitizeCamelCase(a.getNombre());

            sb.append("    ").append(javaType).append(" ").append(fieldName);
            if (i < targetList.size() - 1) sb.append(",\n");
        }

        sb.append("\n) {}\n");
        return sb.toString();
    }

    private String generarResponseDto(String basePackage, Clase clase, List<Atributo> atributos) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".dto;\n\n");

        Set<String> typeImports = collectTypeImports(atributos);
        for (String imp : typeImports) {
            sb.append(imp).append("\n");
        }
        sb.append("\n");

        sb.append("public record ").append(clase.getNombre()).append("ResponseDTO(\n");

        boolean hasExplicitPk = atributos.stream().anyMatch(a -> Boolean.TRUE.equals(a.getEsPk()));
        boolean first = true;

        if (!hasExplicitPk) {
            sb.append("    Long id");
            first = false;
        }

        for (Atributo a : atributos) {
            if (!first) sb.append(",\n");
            String javaType = normalizeJavaType(a.getTipoDato());
            String fieldName = sanitizeCamelCase(a.getNombre());
            sb.append("    ").append(javaType).append(" ").append(fieldName);
            first = false;
        }

        sb.append("\n) {}\n");
        return sb.toString();
    }

    private String generarRepository(String basePackage, Clase clase, List<Atributo> atributos) {
        String pkType = resolvePkType(atributos);
        Set<String> typeImports = collectTypeImports(atributos);

        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".repository;\n\n");
        sb.append("import ").append(basePackage).append(".entity.").append(clase.getNombre()).append(";\n");
        sb.append("import org.springframework.data.jpa.repository.JpaRepository;\n");
        sb.append("import org.springframework.stereotype.Repository;\n");

        for (String imp : typeImports) {
            if (imp.contains(pkType)) {
                sb.append(imp).append("\n");
            }
        }
        sb.append("\n");

        sb.append("@Repository\n");
        sb.append("public interface ").append(clase.getNombre()).append("Repository extends JpaRepository<")
                .append(clase.getNombre()).append(", ").append(pkType).append("> {\n");
        sb.append("}\n");

        return sb.toString();
    }

    private String generarService(String basePackage, Clase clase, List<Atributo> atributos) {
        String className = clase.getNombre();
        String pkType = resolvePkType(atributos);
        Set<String> typeImports = collectTypeImports(atributos);

        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".service;\n\n");
        sb.append("import ").append(basePackage).append(".dto.").append(className).append("RequestDTO;\n");
        sb.append("import ").append(basePackage).append(".dto.").append(className).append("ResponseDTO;\n");
        sb.append("import ").append(basePackage).append(".entity.").append(className).append(";\n");
        sb.append("import ").append(basePackage).append(".repository.").append(className).append("Repository;\n");
        sb.append("import org.springframework.stereotype.Service;\n");
        sb.append("import org.springframework.transaction.annotation.Transactional;\n\n");
        sb.append("import java.util.List;\n");
        sb.append("import java.util.Optional;\n");
        sb.append("import java.util.stream.Collectors;\n");

        for (String imp : typeImports) {
            sb.append(imp).append("\n");
        }
        sb.append("\n");

        sb.append("@Service\n");
        sb.append("@Transactional\n");
        sb.append("public class ").append(className).append("Service {\n\n");
        sb.append("    private final ").append(className).append("Repository repository;\n\n");
        sb.append("    public ").append(className).append("Service(").append(className).append("Repository repository) {\n");
        sb.append("        this.repository = repository;\n");
        sb.append("    }\n\n");

        // 1. GET all
        sb.append("    @Transactional(readOnly = true)\n");
        sb.append("    public List<").append(className).append("ResponseDTO> findAll() {\n");
        sb.append("        return repository.findAll().stream()\n");
        sb.append("                .map(this::toResponseDTO)\n");
        sb.append("                .collect(Collectors.toList());\n");
        sb.append("    }\n\n");

        // 2. GET by ID
        sb.append("    @Transactional(readOnly = true)\n");
        sb.append("    public Optional<").append(className).append("ResponseDTO> findById(").append(pkType).append(" id) {\n");
        sb.append("        return repository.findById(id).map(this::toResponseDTO);\n");
        sb.append("    }\n\n");

        // 3. POST create
        sb.append("    public ").append(className).append("ResponseDTO create(").append(className).append("RequestDTO dto) {\n");
        sb.append("        ").append(className).append(" entity = toEntity(dto);\n");
        sb.append("        ").append(className).append(" saved = repository.save(entity);\n");
        sb.append("        return toResponseDTO(saved);\n");
        sb.append("    }\n\n");

        // 4. PUT update
        sb.append("    public Optional<").append(className).append("ResponseDTO> update(").append(pkType).append(" id, ").append(className).append("RequestDTO dto) {\n");
        sb.append("        return repository.findById(id).map(existing -> {\n");
        sb.append("            updateEntityFromDTO(existing, dto);\n");
        sb.append("            ").append(className).append(" updated = repository.save(existing);\n");
        sb.append("            return toResponseDTO(updated);\n");
        sb.append("        });\n");
        sb.append("    }\n\n");

        // 5. DELETE
        sb.append("    public boolean deleteById(").append(pkType).append(" id) {\n");
        sb.append("        if (repository.existsById(id)) {\n");
        sb.append("            repository.deleteById(id);\n");
        sb.append("            return true;\n");
        sb.append("        }\n");
        sb.append("        return false;\n");
        sb.append("    }\n\n");

        // Mapper toResponseDTO
        sb.append("    private ").append(className).append("ResponseDTO toResponseDTO(").append(className).append(" entity) {\n");
        sb.append("        return new ").append(className).append("ResponseDTO(\n");

        boolean hasExplicitPk = atributos.stream().anyMatch(a -> Boolean.TRUE.equals(a.getEsPk()));
        boolean first = true;
        if (!hasExplicitPk) {
            sb.append("            entity.getId()");
            first = false;
        }

        for (Atributo a : atributos) {
            if (!first) sb.append(",\n");
            String getter = "get" + capitalize(sanitizeCamelCase(a.getNombre())) + "()";
            sb.append("            entity.").append(getter);
            first = false;
        }
        sb.append("\n        );\n");
        sb.append("    }\n\n");

        // Mapper toEntity
        sb.append("    private ").append(className).append(" toEntity(").append(className).append("RequestDTO dto) {\n");
        sb.append("        ").append(className).append(" entity = new ").append(className).append("();\n");
        sb.append("        updateEntityFromDTO(entity, dto);\n");
        sb.append("        return entity;\n");
        sb.append("    }\n\n");

        // Mapper updateEntityFromDTO
        sb.append("    private void updateEntityFromDTO(").append(className).append(" entity, ").append(className).append("RequestDTO dto) {\n");
        for (Atributo a : atributos) {
            if (Boolean.TRUE.equals(a.getEsPk()) || a.getNombre().equalsIgnoreCase("id")) {
                continue;
            }
            String fieldName = sanitizeCamelCase(a.getNombre());
            String setter = "set" + capitalize(fieldName);
            sb.append("        entity.").append(setter).append("(dto.").append(fieldName).append("());\n");
        }
        sb.append("    }\n");

        sb.append("}\n");
        return sb.toString();
    }

    private String generarController(String basePackage, Clase clase, List<Atributo> atributos) {
        String className = clase.getNombre();
        String pkType = resolvePkType(atributos);
        String pkGetter = resolvePkGetterName(atributos);
        String endpointPath = sanitizeIdentifier(className).toLowerCase() + "s";
        Set<String> typeImports = collectTypeImports(atributos);

        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".controller;\n\n");
        sb.append("import ").append(basePackage).append(".dto.").append(className).append("RequestDTO;\n");
        sb.append("import ").append(basePackage).append(".dto.").append(className).append("ResponseDTO;\n");
        sb.append("import ").append(basePackage).append(".service.").append(className).append("Service;\n");
        sb.append("import jakarta.validation.Valid;\n");
        sb.append("import org.springframework.http.HttpStatus;\n");
        sb.append("import org.springframework.http.ResponseEntity;\n");
        sb.append("import org.springframework.web.bind.annotation.*;\n\n");
        sb.append("import java.net.URI;\n");
        sb.append("import java.util.List;\n");

        for (String imp : typeImports) {
            if (imp.contains(pkType)) {
                sb.append(imp).append("\n");
            }
        }
        sb.append("\n");

        sb.append("@RestController\n");
        sb.append("@RequestMapping(\"/api/").append(endpointPath).append("\")\n");
        sb.append("@CrossOrigin(originPatterns = \"*\")\n");
        sb.append("public class ").append(className).append("Controller {\n\n");
        sb.append("    private final ").append(className).append("Service service;\n\n");
        sb.append("    public ").append(className).append("Controller(").append(className).append("Service service) {\n");
        sb.append("        this.service = service;\n");
        sb.append("    }\n\n");

        // 1. GET ALL
        sb.append("    @GetMapping\n");
        sb.append("    public ResponseEntity<List<").append(className).append("ResponseDTO>> findAll() {\n");
        sb.append("        return ResponseEntity.ok(service.findAll());\n");
        sb.append("    }\n\n");

        // 2. GET BY ID
        sb.append("    @GetMapping(\"/{id}\")\n");
        sb.append("    public ResponseEntity<").append(className).append("ResponseDTO> findById(@PathVariable ").append(pkType).append(" id) {\n");
        sb.append("        return service.findById(id)\n");
        sb.append("                .map(ResponseEntity::ok)\n");
        sb.append("                .orElseGet(() -> ResponseEntity.notFound().build());\n");
        sb.append("    }\n\n");

        // 3. POST CREATE
        sb.append("    @PostMapping\n");
        sb.append("    public ResponseEntity<").append(className).append("ResponseDTO> create(@Valid @RequestBody ").append(className).append("RequestDTO dto) {\n");
        sb.append("        ").append(className).append("ResponseDTO created = service.create(dto);\n");
        sb.append("        URI location = URI.create(\"/api/").append(endpointPath).append("/\" + created.").append(pkGetter).append("());\n");
        sb.append("        return ResponseEntity.status(HttpStatus.CREATED).location(location).body(created);\n");
        sb.append("    }\n\n");

        // 4. PUT UPDATE
        sb.append("    @PutMapping(\"/{id}\")\n");
        sb.append("    public ResponseEntity<").append(className).append("ResponseDTO> update(@PathVariable ").append(pkType).append(" id, @Valid @RequestBody ").append(className).append("RequestDTO dto) {\n");
        sb.append("        return service.update(id, dto)\n");
        sb.append("                .map(ResponseEntity::ok)\n");
        sb.append("                .orElseGet(() -> ResponseEntity.notFound().build());\n");
        sb.append("    }\n\n");

        // 5. DELETE
        sb.append("    @DeleteMapping(\"/{id}\")\n");
        sb.append("    public ResponseEntity<Void> deleteById(@PathVariable ").append(pkType).append(" id) {\n");
        sb.append("        if (service.deleteById(id)) {\n");
        sb.append("            return ResponseEntity.noContent().build();\n");
        sb.append("        }\n");
        sb.append("        return ResponseEntity.notFound().build();\n");
        sb.append("    }\n");

        sb.append("}\n");
        return sb.toString();
    }

    // =========================================================================
    // HELPER & UTILITY METHODS
    // =========================================================================

    private String normalizeJavaType(String rawType) {
        if (rawType == null || rawType.isBlank()) return "String";
        String t = rawType.trim().toLowerCase();

        if (t.equals("string") || t.contains("varchar") || t.contains("char") || t.contains("text")) return "String";
        if (t.equals("int") || t.equals("integer") || t.contains("entero") || t.equals("smallint")) return "Integer";
        if (t.equals("long") || t.equals("bigint") || t.equals("id")) return "Long";
        if (t.equals("double") || t.equals("float") || t.equals("real")) return "Double";
        if (t.contains("bigdecimal") || t.contains("decimal") || t.contains("numeric") || t.contains("money") || t.contains("precio") || t.contains("monto")) return "BigDecimal";
        if (t.equals("boolean") || t.equals("bool")) return "Boolean";
        if (t.equals("localdate") || t.equals("date") || t.contains("fecha") && !t.contains("hora")) return "LocalDate";
        if (t.equals("localdatetime") || t.equals("datetime") || t.equals("timestamp") || t.contains("fechahora")) return "LocalDateTime";
        if (t.equals("localtime") || t.equals("time") || t.contains("hora")) return "LocalTime";
        if (t.equals("uuid") || t.equals("guid")) return "UUID";
        if (t.equals("byte[]") || t.equals("blob") || t.equals("bytes")) return "byte[]";

        return capitalize(rawType.replaceAll("[^A-Za-z0-9_]", ""));
    }

    private String mapJavaTypeToSql(String javaType) {
        if (javaType == null) return "VARCHAR(255)";
        return switch (javaType) {
            case "String" -> "VARCHAR(255)";
            case "Integer" -> "INT";
            case "Long" -> "BIGINT";
            case "Double" -> "DOUBLE PRECISION";
            case "BigDecimal" -> "NUMERIC(19, 4)";
            case "Boolean" -> "BOOLEAN";
            case "LocalDate" -> "DATE";
            case "LocalDateTime" -> "TIMESTAMP WITHOUT TIME ZONE";
            case "LocalTime" -> "TIME WITHOUT TIME ZONE";
            case "UUID" -> "UUID";
            case "byte[]" -> "BYTEA";
            default -> "VARCHAR(255)";
        };
    }

    private Set<String> collectTypeImports(List<Atributo> atributos) {
        Set<String> imports = new TreeSet<>();
        if (atributos == null) return imports;

        for (Atributo a : atributos) {
            String javaType = normalizeJavaType(a.getTipoDato());
            switch (javaType) {
                case "LocalDate" -> imports.add("import java.time.LocalDate;");
                case "LocalDateTime" -> imports.add("import java.time.LocalDateTime;");
                case "LocalTime" -> imports.add("import java.time.LocalTime;");
                case "BigDecimal" -> imports.add("import java.math.BigDecimal;");
                case "UUID" -> imports.add("import java.util.UUID;");
            }
        }
        return imports;
    }

    private String resolvePkType(List<Atributo> atributos) {
        if (atributos != null) {
            for (Atributo a : atributos) {
                if (Boolean.TRUE.equals(a.getEsPk())) {
                    return normalizeJavaType(a.getTipoDato());
                }
            }
        }
        return "Long";
    }

    private String resolvePkGetterName(List<Atributo> atributos) {
        if (atributos != null) {
            for (Atributo a : atributos) {
                if (Boolean.TRUE.equals(a.getEsPk())) {
                    return sanitizeCamelCase(a.getNombre());
                }
            }
        }
        return "id";
    }

    private String sanitizeIdentifier(String raw) {
        if (raw == null || raw.isBlank()) return "tabla";
        return raw.replaceAll("[^A-Za-z0-9_]", "_").toLowerCase();
    }

    private String sanitizeCamelCase(String raw) {
        if (raw == null || raw.isBlank()) return "campo";
        String clean = raw.replaceAll("[^A-Za-z0-9_]", "");
        if (clean.isEmpty()) return "campo";
        return clean.substring(0, 1).toLowerCase() + clean.substring(1);
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) return str;
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}
